group = io.github.ohsoou
version = 0.2.0

pluginId = io.github.ohsoou.trans-md
pluginName = Trans MD
pluginVendorName = ohsoou
pluginVendorEmail = soouleaf@gmail.com

platformVersion = 2024.3
platformType = IC

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true